server:
  port: 9002

# 유레카 서버 설정
#eureka:
#  client:
#  service-url:
#    defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    jwt:
      signkey: planit

spring:
#  application:
#    name: todo-service
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/PLANIT_TODO?useUnicode=true&charaterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    hikari:
      username: planit
      password: planit1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect
    hibernate:
      ddl-auto: create